// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export { Data } from './properties/data.js';
export { Entity } from './properties/entity.js';
export { Rel } from './properties/rel.js';
export { SpatialStructure } from './properties/spatial-structure.js';
