// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export { Data } from './entities/data.js';
export { Entity } from './entities/entity.js';
export { Rel } from './entities/rel.js';
export { SpatialStructure } from './entities/spatial-structure.js';
