// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class ExpressIDAttribute {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ExpressIDAttribute {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsExpressIDAttribute(bb:flatbuffers.ByteBuffer, obj?:ExpressIDAttribute):ExpressIDAttribute {
  return (obj || new ExpressIDAttribute()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsExpressIDAttribute(bb:flatbuffers.ByteBuffer, obj?:ExpressIDAttribute):ExpressIDAttribute {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ExpressIDAttribute()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

value():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startExpressIDAttribute(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addValue(builder:flatbuffers.Builder, value:number) {
  builder.addFieldInt32(0, value, 0);
}

static endExpressIDAttribute(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createExpressIDAttribute(builder:flatbuffers.Builder, value:number):flatbuffers.Offset {
  ExpressIDAttribute.startExpressIDAttribute(builder);
  ExpressIDAttribute.addValue(builder, value);
  return ExpressIDAttribute.endExpressIDAttribute(builder);
}
}
