// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class TypeValue {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TypeValue {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTypeValue(bb:flatbuffers.ByteBuffer, obj?:TypeValue):TypeValue {
  return (obj || new TypeValue()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTypeValue(bb:flatbuffers.ByteBuffer, obj?:TypeValue):TypeValue {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TypeValue()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

value():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startTypeValue(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addValue(builder:flatbuffers.Builder, value:bigint) {
  builder.addFieldInt64(0, value, BigInt('0'));
}

static endTypeValue(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTypeValue(builder:flatbuffers.Builder, value:bigint):flatbuffers.Offset {
  TypeValue.startTypeValue(builder);
  TypeValue.addValue(builder, value);
  return TypeValue.endTypeValue(builder);
}
}
