// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ValueType {
  UNKNOWN = 0,
  STRING = 1,
  LABEL = 2,
  ENUM = 3,
  REAL = 4,
  REF = 5,
  EMPTY = 6
}
