// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Rel {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Rel {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRel(bb:flatbuffers.ByteBuffer, obj?:Rel):Rel {
  return (obj || new Rel()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRel(bb:flatbuffers.ByteBuffer, obj?:Rel):Rel {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Rel()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

defs(index: number):string
defs(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
defs(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

defsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startRel(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addDefs(builder:flatbuffers.Builder, defsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, defsOffset, 0);
}

static createDefsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startDefsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endRel(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRel(builder:flatbuffers.Builder, defsOffset:flatbuffers.Offset):flatbuffers.Offset {
  Rel.startRel(builder);
  Rel.addDefs(builder, defsOffset);
  return Rel.endRel(builder);
}
}
